# See https://redoc.ly/docs/cli/configuration/ for more information.
apis:
  decorators@v1: 
    root: openapi/openapi.yaml
lint:
  extends:
    - recommended
features.openapi:
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "blue"
      error:
        main: "#abcabc"
      http:
        put: "black"
  generateCodeSamples:
    languages:
      - lang: curl 
      - lang: "Node.js"
      - lang: "JavaScript"
      